[package]
name = "gen-id"
description = "Snowflakes."
version = "0.2.1"
edition = "2021"
license = "MIT"
repository = "ssh://git@github.com/wavey-ai/gen-id"
readme = "README.md"

[dependencies]
rand = "0.8.5"
